### ISSUE TITLE
Add exceptions handeling to OpcService, refactor api entry point

### ISSUE THREAD

**Issue by YaraZan** [YaraZan/next-scada#5]
**Description:**

This issue covers the refactoring and enhancement of the OPC Service functionality. 
---

**Tasks:**
- [x] Add `Host` property to `OpcServer` base class.
- [x] Pass `Host` property in `BrowseDaServers` and `BrowseUaServers`.
- [x] Add custom exceptions for OPC operations (browsing, creating, reading).
- [x] Handle timeout in OPC browsing operations.
- [x] Parse URLs and hosts from `appsettings.json`.
- [x] Remove `api.http` file as unnecessary.
- [x] Fix API endpoint paths in `OpcController`.
- [x] Add `DotNetEnv` package for parsing environment variables.
- [x] Add allowed hosts and base URL configuration in `appsettings.json`.

**Comment by YaraZan** [comment]
Add `DotNetEnv` package for parsing environment variables

**Comment by YaraZan** [comment]
Add exceptions for OPC-related actions

**Comment by YaraZan** [comment]
Tests shouldn`t  be implemented on this stage. Pull request will be created anyways
